### PR TITLE
make this work on centos

### PR DESCRIPTION
**Pull request by kplimack**
cause this is what we want to happen

### CODE REVIEW

**Comment by tas50** [comment]
@kplimack On CentOS won't modifying the /etc/motd file overwrite the entire MOTD vs. motd.tail on debian systems that just appends?

**Comment by kplimack** [comment]
yes, it will just clobber it, but the goal is to login to every system and
see the same greeting and info, right?
I'd like to use this cookbook agnostically to produce a basic motd that
tells me what a node does.

**Comment by iennae** [comment]
@kplimack can you change it to match the functionality of debian systems? This cookbook is the motd-tail cookbook and we should just append versus overwrite.

**Comment by kplimack** [comment]
@iennae I totally agree, just not sure its currently doable.  I'll do some more digging and see what I can come up with.

**Comment by tas50** [comment]
Closing this out since it sounds like we agree centos vs. debian is hard

**Pull request closed without merging**
